[account]

[ipc]
disable = true

[mining]
extra_data = "Parity"
force_sealing = true
min_gas_price = 1000000000
reseal_min_period = 0
reseal_on_txs = "none"

[misc]
log_file = "parity.log"
logging = ""

[network]
interface = "all"
nat = "none"
port = 30300
reserved_peers = "reserved-peers"

[parity]
base_path = "data"
chain = "spec.json"

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "personal", "traces", "rpc", "shh", "shh_pubsub"]
cors = ["all"]
hosts = ["all"]
interface = "all"
port = 8540

[secretstore]
disable = true

[ui]
disable = true

[websockets]
interface = "all"
origins = ["all"]
port = 9540
